Repository bitzquad/bitzquad.com, pull requests merged in 2022-03, with the labels that each got.

#70 Preserve package-lock
  .github/workflows/node.build.yml
Labels: bug

#73 ✨feat: create hero section
  .github/pull_request_template.md
  src/app.scss
  src/lib/Footer.svelte
  src/lib/Home/HeroSection.svelte
  src/lib/Navbar.svelte
  src/routes/[pages]/index.svelte
  static/heroImage.svg
Labels: enhancement

#74 Feature/404page
  src/app.html
  src/lib/Footer.svelte
  src/lib/Navbar.svelte
  src/routes/[pages]/index.svelte
  src/routes/[pages]/social/[index].svelte
  src/routes/__error.svelte
  src/routes/__layout.svelte
  static/404-error.svg
  static/bug-fix.svg
Labels: bug, enhancement

#75 🚧 Update Landing page & improve page quality
  src/app.html
  src/app.scss
  src/lib/Components/ServiceCard.svelte
  src/lib/Footer.svelte
  src/lib/Home/HeroSection.svelte
  src/lib/Home/ServicesSection.svelte
  src/lib/Home/WorldWithUs.svelte
  src/lib/Navbar.svelte
  src/routes/[pages]/SamplePage-Text.ts
  src/routes/[pages]/__layout.svelte
  src/routes/[pages]/about.svelte
  src/routes/[pages]/contact.svelte
  src/routes/[pages]/index.svelte
  src/routes/[pages]/location.svelte
  src/routes/[pages]/news.svelte
  src/routes/[pages]/school.svelte
  src/routes/[pages]/social/[index].svelte
  src/routes/[pages]/team.svelte
  src/routes/__error.svelte
  src/routes/__layout.svelte
  static/brand.png
  static/ecommerce.png
  static/ethereum.png
  static/mobile.png
  static/services.svg
  static/social.png
  static/web.svg
  static/world.svg
Labels: enhancement

#77 🐛:fix: get static from BASE_DIR
  src/lib/Home/HeroSection.svelte
  src/lib/Home/ServicesSection.svelte
  src/lib/Home/WorldWithUs.svelte
Labels: bug

#84 🐛:fix: Rename Message section and Improve styles
  src/app.scss
  src/lib/Components/ContactForm.svelte
  src/lib/Home/HeroSection.svelte
  src/routes/[pages]/contact.svelte
Labels: bug
